// Maps html_file paths to per-note JS slugs.
const NOTES_MANIFEST = {
  "HTML/YR 1 SEM 1/1900 BUGANDA AGREEMENT.html": "yr-1-sem-1-1900-buganda-agreement",
  "HTML/YR 1 SEM 1/COMMUNICATION SKILLS NOTES .html": "yr-1-sem-1-communication-skills-notes",
  "HTML/YR 1 SEM 1/COMMUNICATION-SKILLS-NOTES-B.html": "yr-1-sem-1-communication-skills-notes-b",
  "HTML/YR 1 SEM 1/CONSTITUTIONAL HISTORY NOTES Dr ONORIA-1(4).html": "yr-1-sem-1-constitutional-history-notes-dr-onoria-1-4",
  "HTML/YR 1 SEM 1/Constitutional History Notes 2021.html": "yr-1-sem-1-constitutional-history-notes-2021",
  "HTML/YR 1 SEM 1/Criminal Law 1 - jorvannotes.html": "yr-1-sem-1-criminal-law-1-jorvannotes",
  "HTML/YR 1 SEM 1/Criminal Law notes K.html": "yr-1-sem-1-criminal-law-notes-k",
  "HTML/YR 1 SEM 1/FOUNDATIONS_OF_LAW_QUESTIONS_AND_ANSWERS_2017[1] (Autosaved).html": "yr-1-sem-1-foundations-of-law-questions-and-answers-2017-1-autosaved",
  "HTML/YR 1 SEM 1/Introducing law notes(1).html": "yr-1-sem-1-introducing-law-notes-1",
  "HTML/YR 1 SEM 1/LEGAL METHODS QUESTIONS AND ANSWERS (1).html": "yr-1-sem-1-legal-methods-questions-and-answers-1",
  "HTML/YR 1 SEM 1/Legal Method Notes 1.html": "yr-1-sem-1-legal-method-notes-1",
  "HTML/YR 1 SEM 1/MU-CONSTITUTIONAL HISTORY NOTES.html": "yr-1-sem-1-mu-constitutional-history-notes",
  "HTML/YR 1 SEM 1/NOTES_ON_CONTRACT_1_and_2_Ug (1).html": "yr-1-sem-1-notes-on-contract-1-and-2-ug-1",
  "HTML/YR 1 SEM 1/Notes_Constitutional_Hist_Finale_A___12_(1)[1].html": "yr-1-sem-1-notes-constitutional-hist-finale-a-12-1-1",
  "HTML/YR 1 SEM 1/constitutional History MUK.html": "yr-1-sem-1-constitutional-history-muk",
  "HTML/YR 1 SEM 2/COMMUNICATION SKILLS NOTES C.html": "yr-1-sem-2-communication-skills-notes-c",
  "HTML/YR 1 SEM 2/CONSTITUTIONAL LAW NOTES   finale.html": "yr-1-sem-2-constitutional-law-notes-finale",
  "HTML/YR 1 SEM 2/Criminal Law 1 - jorvannotes.html": "yr-1-sem-2-criminal-law-1-jorvannotes",
  "HTML/YR 1 SEM 2/LAW OF CONTRACT-2 Notes.html": "yr-1-sem-2-law-of-contract-2-notes",
  "HTML/YR 1 SEM 2/LEGAL METHODS QUESTIONS AND ANSWERS (1).html": "yr-1-sem-2-legal-methods-questions-and-answers-1",
  "HTML/YR 1 SEM 2/LLB Fundamentals of Criminal Law Notes.html": "yr-1-sem-2-llb-fundamentals-of-criminal-law-notes",
  "HTML/YR 1 SEM 2/Legal Method Notes 1.html": "yr-1-sem-2-legal-method-notes-1",
  "HTML/YR 1 SEM 2/SHISA_ROBERT_STRICT_LIABILITY_NOTES.html": "yr-1-sem-2-shisa-robert-strict-liability-notes",
  "HTML/YR 2 SEM 1/ADMINISTRATIVE LAW 2.html": "yr-2-sem-1-administrative-law-2",
  "HTML/YR 2 SEM 1/ADMINISTRATIVE LAW sammary.html": "yr-2-sem-1-administrative-law-sammary",
  "HTML/YR 2 SEM 1/Company-law-Notespdf.html": "yr-2-sem-1-company-law-notespdf",
  "HTML/YR 2 SEM 1/Escalating Land Conflicts in Uganda.html": "yr-2-sem-1-escalating-land-conflicts-in-uganda",
  "HTML/YR 2 SEM 1/FAMILY_LAW_NOTES.html": "yr-2-sem-1-family-law-notes",
  "HTML/YR 2 SEM 1/Full Administrative Law Reading List and Class Notes_1 - Copy.html": "yr-2-sem-1-full-administrative-law-reading-list-and-class-notes-1-copy",
  "HTML/YR 2 SEM 1/LAND_LAW_MAIN_NOTES_2[1].html": "yr-2-sem-1-land-law-main-notes-2-1",
  "HTML/YR 2 SEM 1/NEGLIGENCE_and_STRICT_LIABILITY._NOTES.pdf (1).html": "yr-2-sem-1-negligence-and-strict-liability-notes-pdf-1",
  "HTML/YR 2 SEM 1/Sale of Goods.html": "yr-2-sem-1-sale-of-goods",
  "HTML/YR 2 SEM 1/family-law-real-notes-1.html": "yr-2-sem-1-family-law-real-notes-1",
  "HTML/YR 2 SEM 2/ TORTS.html": "yr-2-sem-2-torts",
  "HTML/YR 2 SEM 2/Business Associations 2 .html": "yr-2-sem-2-business-associations-2",
  "HTML/YR 2 SEM 2/EQUITY AND TRUST Q&A.html": "yr-2-sem-2-equity-and-trust-q-a",
  "HTML/YR 2 SEM 2/EQUITY AND TRUSTS NOTES 2021.html": "yr-2-sem-2-equity-and-trusts-notes-2021",
  "HTML/YR 2 SEM 2/Full Admin 2 Notes.html": "yr-2-sem-2-full-admin-2-notes",
  "HTML/YR 2 SEM 2/LAW_OF_SALE_OF_GOODS_NOTES.html": "yr-2-sem-2-law-of-sale-of-goods-notes",
  "HTML/YR 2 SEM 2/LIABILITY OF GOODS.html": "yr-2-sem-2-liability-of-goods",
  "HTML/YR 2 SEM 2/LLB Environmental Law Notes.html": "yr-2-sem-2-llb-environmental-law-notes",
  "HTML/YR 2 SEM 2/Land Law II-Lecture notes. copy.html": "yr-2-sem-2-land-law-ii-lecture-notes-copy",
  "HTML/YR 2 SEM 2/Land Law II-Lecture notes..html": "yr-2-sem-2-land-law-ii-lecture-notes",
  "HTML/YR 2 SEM 2/NEGLIGENCE and STRICT LIABILITY. NOTES.html": "yr-2-sem-2-negligence-and-strict-liability-notes",
  "HTML/YR 2 SEM 2/Tort class material NOTES .html": "yr-2-sem-2-tort-class-material-notes",
  "HTML/YR 2 SEM 2/_EXPROPRIATED_PROPERTIES.html": "yr-2-sem-2-expropriated-properties",
  "HTML/YR 2 SEM 2/company-law-2-aziz.html": "yr-2-sem-2-company-law-2-aziz",
  "HTML/YR 2 SEM 2/equitable redemtion of mortgages.html": "yr-2-sem-2-equitable-redemtion-of-mortgages",
  "HTML/YR 2 SEM 2/family-2-notes.html": "yr-2-sem-2-family-2-notes",
  "HTML/YR 2 SEM 2/land law 2- kitata (mortgage).html": "yr-2-sem-2-land-law-2-kitata-mortgage",
  "HTML/YR 2 SEM 2/theories of ownership.html": "yr-2-sem-2-theories-of-ownership",
  "HTML/YR 3 SEM 1/BANKING - QNS & ANS - FINAL.html": "yr-3-sem-1-banking-qns-ans-final",
  "HTML/YR 3 SEM 1/Banking Law notes docx.html": "yr-3-sem-1-banking-law-notes-docx",
  "HTML/YR 3 SEM 1/Business Associations 2 .html": "yr-3-sem-1-business-associations-2",
  "HTML/YR 3 SEM 1/CIVIL PROCEDURE 1 NOTES copy.html": "yr-3-sem-1-civil-procedure-1-notes-copy",
  "HTML/YR 3 SEM 1/CIVIL PROCEDURE 1 NOTES.html": "yr-3-sem-1-civil-procedure-1-notes",
  "HTML/YR 3 SEM 1/Civil procedure 1 best notes.html": "yr-3-sem-1-civil-procedure-1-best-notes",
  "HTML/YR 3 SEM 1/GENDER CW GROUP SEVEN.html": "yr-3-sem-1-gender-cw-group-seven",
  "HTML/YR 3 SEM 1/NATURAL_THEORY_OF_LAW[2] (1).html": "yr-3-sem-1-natural-theory-of-law-2-1",
  "HTML/YR 3 SEM 1/international-trade.html": "yr-3-sem-1-international-trade",
  "HTML/YR 3 SEM 1/jurisprudence-Unit-I.html": "yr-3-sem-1-jurisprudence-unit-i",
  "HTML/YR 3 SEM 1/partnership notes class-2.html": "yr-3-sem-1-partnership-notes-class-2",
  "HTML/YR 3 SEM 1/the-law-of-insurance-class-notes.html": "yr-3-sem-1-the-law-of-insurance-class-notes",
  "HTML/YR 3 SEM 2/BUSINESS LAW NOTES GUIDANCE NOTES.html": "yr-3-sem-2-business-law-notes-guidance-notes",
  "HTML/YR 3 SEM 2/CIVIL PROCEDURE 2 NOTES (1).html": "yr-3-sem-2-civil-procedure-2-notes-1",
  "HTML/YR 3 SEM 2/CIVIL PROCEDURE.html": "yr-3-sem-2-civil-procedure",
  "HTML/YR 3 SEM 2/CONDOMINIUM_PROPERTY_IN_UGANDA[1].html": "yr-3-sem-2-condominium-property-in-uganda-1",
  "HTML/YR 3 SEM 2/EVIDENCE 2 NOTES-12.html": "yr-3-sem-2-evidence-2-notes-12",
  "HTML/YR 3 SEM 2/Grounds for Judicial Review.html": "yr-3-sem-2-grounds-for-judicial-review",
  "HTML/YR 3 SEM 2/INSURANCE LAW - Evening Class- Mr Ntegyereize Alauterio (1).html": "yr-3-sem-2-insurance-law-evening-class-mr-ntegyereize-alauterio-1",
  "HTML/YR 3 SEM 2/INSURANCE LAW CLASS NOTES Revised.html": "yr-3-sem-2-insurance-law-class-notes-revised",
  "HTML/YR 3 SEM 2/Insurance Summary.html": "yr-3-sem-2-insurance-summary",
  "HTML/YR 3 SEM 2/International Organizations.html": "yr-3-sem-2-international-organizations",
  "HTML/YR 3 SEM 2/LAW OF EVIDENCE 11.html": "yr-3-sem-2-law-of-evidence-11",
  "HTML/YR 3 SEM 2/international-law-2-notes-uganda (2).html": "yr-3-sem-2-international-law-2-notes-uganda-2",
  "HTML/YR 3 SEM 2/jurisprudence 1 notes nuru2.html": "yr-3-sem-2-jurisprudence-1-notes-nuru2",
  "HTML/YR 3 SEM 2/notes-on-international-dispute-settlement.html": "yr-3-sem-2-notes-on-international-dispute-settlement",
  "HTML/YR 3 SEM 2/principles-of-intl-state-recognition (1).html": "yr-3-sem-2-principles-of-intl-state-recognition-1",
  "HTML/YR 3 SEM 2/the-law-of-use-of-force-lecture-notes (1) (1).html": "yr-3-sem-2-the-law-of-use-of-force-lecture-notes-1-1",
  "HTML/YR 3 SEM 2/time-present-and-time-past-lord-reed-lecture.html": "yr-3-sem-2-time-present-and-time-past-lord-reed-lecture",
  "HTML/YR 4 SEM 1/Copy-Revenue Law and Taxation I.html": "yr-4-sem-1-copy-revenue-law-and-taxation-i",
  "HTML/YR 4 SEM 1/Feminist theory and the Law.html": "yr-4-sem-1-feminist-theory-and-the-law",
  "HTML/YR 4 SEM 1/INTELLECTUAL PROPERTY FAIR.html": "yr-4-sem-1-intellectual-property-fair",
  "HTML/YR 4 SEM 1/INTERNATIONAL AND REGIONAL HUMAN RIGHTS REGIMES.html": "yr-4-sem-1-international-and-regional-human-rights-regimes",
  "HTML/YR 4 SEM 1/Legal Research Methodology by Kasim Balarabe-1.html": "yr-4-sem-1-legal-research-methodology-by-kasim-balarabe-1",
  "HTML/YR 4 SEM 1/RESEARCH METHODS NOTES.docx  GROUPS COMBINED .html": "yr-4-sem-1-research-methods-notes-docx-groups-combined",
  "HTML/YR 4 SEM 1/RESEARCH NOTES LECTURE.html": "yr-4-sem-1-research-notes-lecture",
  "HTML/YR 4 SEM 1/human rights-1[1].html": "yr-4-sem-1-human-rights-1-1",
  "HTML/YR 4 SEM 1/interlectual-property-one.html": "yr-4-sem-1-interlectual-property-one",
  "HTML/YR 4 SEM 1/patent-lecture-notes.html": "yr-4-sem-1-patent-lecture-notes",
  "HTML/YR 4 SEM 1/research-methods-notes.html": "yr-4-sem-1-research-methods-notes",
  "HTML/YR 4 SEM 2/GENDER CW GROUP SEVEN.html": "yr-4-sem-2-gender-cw-group-seven",
  "HTML/YR 4 SEM 2/INTELLECTUAL PROPERTY FAIR.html": "yr-4-sem-2-intellectual-property-fair",
  "HTML/YR 4 SEM 2/Legal Research Methodology by Kasim Balarabe-1.html": "yr-4-sem-2-legal-research-methodology-by-kasim-balarabe-1",
  "HTML/YR 4 SEM 2/jurisprudence-Unit-I.html": "yr-4-sem-2-jurisprudence-unit-i"
};
